# Site settings
title: "I'm Thinking"
subtitle: Programming & Life
email: zlx.star@gmail.com
baseurl: "/" # the subpath of your site, e.g. /blog
url: http://zlx.github.com
author: zlx_star
en_author: Newell
cover: "assets/header_image.jpg"
logo: "assets/logo.png"

excerpt_separator: "<!--more-->"

# Build settings
markdown: kramdown

permalink: /blog/:year/:month/:day/:title/

# Where things are
source:       source
destination:  _site
plugins_dir:  source/_plugins
layouts_dir:  source/_layouts
includes_dir: source/_includes
collections:  null

jekyll-archives:
  enabled: 
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

gems: ['jekyll-archives']

# Config for exclude_home
exclude_home: 'life'

# paginate config
paginate: 10

disqus_shortname: zlx

social:
  - name: Twitter
    icon: twitter
    username: "@zlx_star"
    url: https://twitter.com/zlx_star
    desc: Follow me on Twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - name: GitHub
    icon: github
    username: zlx
    url: https://github.com/zlx
    desc: Fork me on GitHub

  - name: LinkedIn
    icon: linkedin
    username: Newell Zhu
    url: https://cn.linkedin.com/in/zlxstar
    desc: Connect with me on LinkedIn
    share_url: //www.linkedin.com/shareArticle
    share_title: ?mini=true
    share_link: "&amp;url="

descriptions:
  - cat: tech
    desc: "Thinking in Programming"

  - cat: life
    desc: "Thinking in Daily Life"

  - cat: 新仔杂谈
    desc: "片段知识及小技巧"

  - cat: travel
    desc: "旅游见闻"

friends:
  - name: Mouseshi
    link: "http://mouseshi.com/"

prose:
  rooturl: 'source'
  siteurl: 'http://zlx.github.io/'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    'source/_posts':
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: 'date'
        field:
          element: 'hidden'
          value: 'CURRENT_DATETIME'
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "comments"
        field:
          element: "button"
          label: "Can Comment?"
          on: 'Receive Comment'
          off: 'Not Receive Comment'
      - name: "published"
        field:
          element: "button"
          label: "Published Now?"
          on: 'Will Publish'
          off: 'Save to Draft'
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tag"
          alterable: true
          placeholder: "Choose Tags"
          options:
            - name: "新仔杂谈"
              value: "新仔杂谈"
            - name: "Rails"
              value: "Rails"
      - name: "category"
        field:
          element: "multiselect"
          label: "Add Category"
          placeholder: "Choose Category"
          options:
            - name: "Tech"
              value: "tech"
            - name: "En"
              value: "en"
            - name: "Life"
              value: "life"
            - name: "Travel"
              value: "travel"
            - name: "新仔杂谈"
              value: "新仔杂谈"
