# Site settings
title: "I'm Thinking"
subtitle: Programming & Life
email: zlx.star@gmail.com
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://zlx.github.com/" # the base hostname & protocol for your site
author: zlx_star
en_author: Newell
cover: "assets/header_image.jpg"
logo: "assets/logo.png"

social:
  - name: Twitter
    username: "@zlx_star"
    url: "https://twitter.com/zlx_star"
  - name: github
    username: "zlx"
    url: "https://github.com/zlx"

# Build settings
markdown: kramdown

permalink: /blog/:year/:month/:day/:title/

# Where things are
source:       .
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
data_dir:     ./_data
includes_dir: ./_includes
collections:  null

jekyll-archives:
  enabled: 
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

gems: ['jekyll-archives']

# Config for exclude_home
exclude_home:
  categories: 'life'

# paginate config
paginate: 10

disqus_shortname: zlx

social:
  - name: Twitter
    icon: twitter
    username: "@zlx_star"
    url: https://twitter.com/zlx_star
    desc: Follow me on Twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="
  - name: GitHub
    icon: github
    username: zlx
    url: https://github.com/zlx
    desc: Fork me on GitHub
    share_url:
    share_title:
    share_link:

descriptions:
  - cat: tech
    desc: "Thinking in Programming"

  - cat: life
    desc: "Thinking in Daily Life"

  - cat: 新仔杂谈
    desc: "一个个人片段知识及小技巧的记录集"
